name: Login
on:
  schedule:
    - cron: '0 12 * * *'
jobs:
  run-login-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install selenium
      - name: Run login script
        run: python login.py
